### ISSUE TITLE
Board on displays first character of each line

### ISSUE THREAD

**Issue by gibb3h** [rjkerrison/ticker-board#1]
```
<script>
    $(document).ready(function(){
        const board = new Board('.create-ticker',{delay:50,count:3})
        board.updateMessages(['Apple', 'Banana', 'Cherry'])      
    });
</script>

<div class="text-center">
    <ul class="create-ticker">    
    </ul>  
</div>
```
only A, B and C are displayed

`<ul class="board"><li><div class="sr-only">Apple</div><div aria-hidden="true" class="ticker-row"><span class="ticker">A</span></div></li><li><div class="sr-only">Banana</div><div aria-hidden="true" class="ticker-row"><span class="ticker">B</span></div></li><li><div class="sr-only">Cherry</div><div aria-hidden="true" class="ticker-row"><span class="ticker">C</span></div></li></ul>`

**Comment by rjkerrison** [comment]
Hi @gibb3h , thanks for raising an issue on this. I was able to reproduce with similar code at the [Ticker board known issues](https://rjkerrison.co.uk/ticker-board/demo/issues) page.

A workaround exists, which is to specify a `size` in the options, like so:

```js
const board = new Board('.create-ticker', { delay: 50, count: 3, size: 7 })
board.updateMessages(['Apple', 'Banana', 'Cherry'])      
```

I'll update documentation to clear this up. It's likely to stay manadatory when using the `Board` class directly because unlike with `RotationBoard`, it won't know the messages and can't choose a sensible default.

**Comment by gibb3h** [comment]
ah! sorry, I didn't notice the known issues page! Thanks for replying :)

**Comment by rjkerrison** [comment]
It's new! Thanks for raising
